"""add PaymentPhotos table

Revision ID: c3b6fd311669
Revises: 5d5f039675c2
Create Date: 2022-04-20 16:54:25.102126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3b6fd311669'
down_revision = '5d5f039675c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymentphotos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payid', sa.Integer(), nullable=True),
    sa.Column('photopath', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paymentphotos')
    # ### end Alembic commands ###
