"""updated

Revision ID: 5d5f039675c2
Revises: c675388bd0a8
Create Date: 2022-04-19 01:54:48.080352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5f039675c2'
down_revision = 'c675388bd0a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pairs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waitingnum', sa.Integer(), nullable=True))
        batch_op.drop_column('accepted')

    with op.batch_alter_table('pairsindex', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pairhash', sa.String(length=20), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createdIn', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('createdIn')

    with op.batch_alter_table('pairsindex', schema=None) as batch_op:
        batch_op.drop_column('pairhash')

    with op.batch_alter_table('pairs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('waitingnum')

    # ### end Alembic commands ###
