"""add createdIn column in Payments field

Revision ID: 73f892dd8a1f
Revises: c675388bd0a8
Create Date: 2022-04-19 01:49:18.706235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f892dd8a1f'
down_revision = 'c675388bd0a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
