"""accept multiple people in one pair

Revision ID: 154119d75007
Revises: 3e4ea92d8e40
Create Date: 2022-04-06 18:52:25.480272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154119d75007'
down_revision = '3e4ea92d8e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pairsindex',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('pairid', sa.Integer(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pairs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pairs', schema=None) as batch_op:
        batch_op.drop_column('name')

    op.drop_table('pairsindex')
    # ### end Alembic commands ###
